#!/bin/bash

# utilisation : ./Anneau-Generique X

# Vérifie si un argument est passé et qu'il s'agit d'un nombre
if [ $# -eq 0 ]; then
    echo "Usage: $0 <number_of_applications>"
    exit 1
fi

n=$1

# Création des FIFO
for i in $(seq 1 $n); do
    mkfifo /tmp/in_A$i /tmp/out_A$i
    mkfifo /tmp/in_C$i /tmp/out_C$i
done

# Lancement des applications
for i in $(seq 1 $n); do
    port=$((4443 + i))
    go run app-base -n A$i -m g -port $port < /tmp/in_A$i > /tmp/out_A$i &
    go run app-control -n C$i < /tmp/in_C$i > /tmp/out_C$i &
done

# Mise en place de la topologie en anneau
for i in $(seq 1 $n); do
    next=$(( (i % n) + 1 ))
    cat /tmp/out_A$i > /tmp/in_C$i &
    cat /tmp/out_C$i | tee /tmp/in_A$i > /tmp/in_C$next &
done

echo "Script exécuté avec $n applications en topologie en anneau."
